import { ApiProperty } from '@nestjs/swagger';

import { IsString } from 'class-validator';

export class LoginDto {
  @ApiProperty({
    description: 'The code returned from GitHub.',
  })
  @IsString()
  readonly code: string;

  @ApiProperty({
    description: 'A unique value generated by the server. This gets passed through from GitHub.',
  })
  @IsString()
  readonly state: string;

  constructor(codeParam = '', stateParam = '') {
    this.code = codeParam;
    this.state = stateParam;
  }
}
